version: '3'
services:
  monitor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["/bin/sh", "-c", "/usr/local/bin/start_exited_containers.sh"]
