pipeline {
    agent any 
    environment {
    DOCKERHUB_CREDENTIALS = credentials('jhonueldockerhub')
    }
    stages { 
        stage('SCM Checkout') {
            steps{
              //  checkout scmGit(branches: [[name: '*/dev03']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/jhonuel/dev03.git']])
            git 'https://github.com/jhonuel/dev03.git'
            }
        }

        stage('Build docker image') {
            steps {  
                sh 'docker build -t jhonuel/test:$BUILD_NUMBER .'
            }
        }
        stage('login to dockerhub') {
            steps{
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('push image') {
            steps{
                
                sh 'docker push jhonuel/test:$BUILD_NUMBER'
            }
        }
}
post {
        always {
            sh 'docker logout'
        }
    }
}
